In [125]:
import numpy as np
import pandas as pd

# Voltages assume no other composition impacts the voltage reading other than manufacturer specified
# This model also assumes the voltages have no noise in the readings and that there is no dynamic impact 



# These functions convert a composition into a voltage by taking the resistance to composition lines,
# relating it to a voltage.
# These voltages are presumed to add together to equal the resulting MOS voltage out


def TGS2610C_voltage(comp):
    #comp[0]=ethanol, comp[1]=hydrogen, comp[2]=methane, comp[3]=isobutane, comp[4]=propane
    compeff=np.zeros(5)
    m=[-0.520537, -0.51098066, -0.52160942, -0.58191744, -0.58191744]
    c=[4.79196019,  4.39143575,  4.06563873,  4.3121193,  4.3121193]
    poly = np.poly1d([m[0], c[0]])
    Vrl=0.0809988
    for i in range (0, 5):
        if comp[i]>10:
            compeff[i]=(m[i]*comp[i]+c[i]-c[0])/m[0]
    compt=np.sum(compeff)   
    if compt!=0:
        Vrl=5000/((6466*np.exp(poly(np.log(compt))))+1000)+0.0809988
    if Vrl>=5:
        Vrl=5
    return Vrl

def TGS2610D_voltage(comp):
    #comp[0]=ethanol, comp[1]=hydrogen, comp[2]=methane, comp[3]=isobutane, comp[4]=propane
    compeff=np.zeros(5)
    Vrl=0.14621129
    m=[-0.0780411, -0.36560724, -0.43630751, -0.5005877, -0.52637503]
    c=[2.79278989,  3.18747072,  3.64038541,  3.73111725, 3.87145149]
    poly = np.poly1d([m[0], c[0]])
    for i in range (0, 5):
        if comp[i]>10:
            compeff[i]=(m[i]*comp[i]+c[i]-c[0])/m[0]
    compt=np.sum(compeff)  
    if compt!=0:
        Vrl=10000/((6466*np.exp(poly(np.log(compt))))+2000)+0.14621129
    if Vrl>=5:
        Vrl=5
    return Vrl

def TGS2611C_voltage(comp):
    #comp[0]=ethanol, comp[1]=hydrogen, comp[2]=methane, comp[3]=isobutane
    compeff=np.zeros(4)
    m=[-0.3711073,-0.35718333,-0.43148312,-0.38669676]
    c=[3.98629003, 3.6974778, 3.69045858, 3.85023112]
    poly = np.poly1d([m[0], c[0]])
    Vrl=0.0809988
    for i in range (0, 4):
        if comp[i]>10:
            compeff[i]=(m[i]*comp[i]+c[i]-c[0])/m[0]
    compt=np.sum(compeff)
    if compt!=0:
        Vrl=10000/((10227*np.exp(poly(np.log(compt))))+2000)+0.0809988
    if Vrl>=5:
        Vrl=5
    return Vrl

def TGS2611E_voltage(comp):
     #comp[0]=ethanol, comp[1]=hydrogen, comp[2]=methane, comp[3]=isobutane
    compeff=np.zeros(4)
    m=[-0.31340759, -0.395091]
    c=[3.25756, 3.39058279]
    Vrl=0.10917793
    poly = np.poly1d([m[0], c[0]])
    for i in range (1, 3):
        if comp[i]>10:
            compeff[i]=(m[i-1]*comp[i]+c[i-1]-c[0])/m[0]
    compt=np.sum(compeff)
    if compt!=0:
        Vrl=10000/((10227*np.exp(poly(np.log(compt))))+2000)+0.10917793
    if Vrl>=5:
        Vrl=5
    return Vrl
    
def TGS821_voltage(comp):
    # 1,2,3,5
    #comp[0]=ethanol, comp[1]=hydrogen, comp[2]=methane, comp[3]=isobutane, comp[4]=propane, 
    #comp[5]= compco, comp[6]=comph2s, comp[7]= comptol, comp[8]= compamm
    a=[-0.03606462,-0.03606462, -3.46777224e-05, -0.02683372, 0 ,-0.00907706]
    b=[0.30449812,0.30449812,-7.23731173e-01,0.11452099,0, -0.47439125]
    c=[3.12124002,3.12124002,  3.27778891e+00,  4.21144913,0,  6.31307329]
    Vrl=0.11989027
    poly = np.poly1d([a[0],  b[0],  c[0]])
    compeff=np.zeros(6)
    for i in [1,2,3,5]:
        if comp[i]>10:
            compeff[i]=abs((math.sqrt(pow(b[0],2)-4.*a[0]*(c[0]-a[1]*pow(comp[1],2)-b[1]*comp[1]-c[1]))-b[0])/(2.*a[0]))                   
    compt=np.sum(compeff)
    if compt!=0:
        Vrl=10000/((1800*np.exp(poly(np.log(compt))))+2000)+0.11989027
    if Vrl>=5:
        Vrl=5
    return Vrl


def TGS2602_voltage(comp):
   # 1 , 2 , 8, 6, 7  
#comp[0]=ethanol, comp[1]=hydrogen, comp[2]=methane, comp[3]=isobutane, comp[4]=propane, 
#comp[5]= compco, comp[6]=comph2s, comp[7]= comptol, comp[8]= compamm
    m=[-0.45174998,-0.45174998, -0.08410579,0,0,0,0,0,0];m[8]=-0.284918; m[6]= -0.34782794; m[7]= -0.59108458
    c=[-0.20899002,-0.20899002, -0.14035422,0,0,0,0,0,0];c[8]= -0.12711518; c[6]= -0.96296; c[7]= -1.15168577
    Vrl=0.05455673
    compeff=np.zeros(10)
    poly = np.poly1d([m[0], c[0]])
    for i in [1 , 2 , 8, 6, 7]:
        if comp[i]>10:
            compeff[i]=(m[i]*comp[i]+c[i]-c[0])/m[0]
    compt=np.sum(compeff)
    if compt!=0:
        Vrl=5000/((90000*np.exp(poly(np.log(compt))))+1000)+0.05455673
    if Vrl>=5:
        Vrl=5
    return Vrl


def TGS2620_voltage(comp):
    # 0 , 1, 2, 3, 5 
#comp[0]=ethanol, comp[1]=hydrogen, comp[2]=methane, comp[3]=isobutane, comp[4]=propane, 
#comp[5]= compco, comp[6]=comph2s, comp[7]= comptol, comp[8]= compamm
    m=[-0.63663885,-0.51568026,-0.41100547,-0.53475486, 0, -0.54209517]
    c=[3.6739128,2.99570642,  4.37689757,  3.3718626, 0 ,  3.9131767]
    Vrl=0.05423905
    poly = np.poly1d([m[0], c[0]])
    compeff=np.zeros(10)
    for i in [0 , 1, 2, 3, 5 ]:
        if comp[i]>10:
            compeff[i]=(m[i]*comp[i]+c[i]-c[0])/m[0]
    compt=np.sum(compeff)
    if compt!=0:
        Vrl=3000/((4286*np.exp(poly(np.log(compt))))+600)+0.05423905
    if Vrl>=5:
        Vrl=5
    return Vrl

# Voltage_Virtual_Nose sends the compositions to each individual MOS and checks for a composition exceeding 1,000,000ppmV

def Voltage_Virtual_Nose(comp):
    
    comp_total= comp[0]+ comp[1]+ comp[2]+comp[3]+comp[4]+ comp[5]+comp[6]+comp[7] + comp[8]+  comp[9]
    if comp_total> 1000001:
        print("error: comp greater than 1000000 ppm")
        return 
    VT=np.array([0.,0.,0.,0.,0.,0.,0.])
    VT[0]= round(TGS2610C_voltage(comp), 3)
    VT[1]= round(TGS2610D_voltage(comp), 3)
    VT[2]= round(TGS2611C_voltage(comp) , 3)
    VT[3]= round(TGS2611E_voltage(comp), 3)
    VT[4]= round(TGS821_voltage(comp), 3)
    VT[5]= round(TGS2602_voltage(comp), 3)
    VT[6]= round(TGS2620_voltage(comp), 3)
    return VT
# competh=1; comphyd=10; compmet=1; compibut=1; compprop=10000; compair=1000000;
# compco=1; comph2s=100; comptol=100; compamm=100


In [126]:
#test case 1, 0 compositions, should reply with base air value 
print("         Test 1: 0 compositions ")
print("")
comp=[0, 0, 0, 0, 0, 0, 0,0, 0, 0]
V=Voltage_Virtual_Nose(comp)
print(V)
print("")
print("check does V = [0.081 0.146 0.113 0.109 0.12  0.055 0.054]")
print("")
#test case 2, composition exceeds 1000000 ppm 
print("         Test 2:  composition exceeds 1000000 ppm ")
print("")
comp=[0, 0, 0, 0, 0,0, 0,0, 0, 2000000]
V=Voltage_Virtual_Nose(comp)
print("")
#test case 3, check for changes V =  [1.553 2.731 0.398 0.469 2.061 2.341 2.587]
print("         Test 3: check for unexpected changes")
print("")
comp=[10, 40, 30, 50, 6000,7000, 80, 50, 300, 10000]
V=Voltage_Virtual_Nose(comp)
print(V)
print("")
print("check does V = [0.645 0.354 0.188 0.252 0.247 0.877 2.434]")

         Test 1: 0 compositions 

[0.081 0.146 0.081 0.109 0.12  0.055 0.054]

check does V = [0.081 0.146 0.113 0.109 0.12  0.055 0.054]

         Test 2:  composition exceeds 1000000 ppm 

error: comp greater than 1000000 ppm

         Test 3: check for unexpected changes

[0.645 0.354 0.188 0.252 0.247 0.877 2.434]

check does V = [0.645 0.354 0.188 0.252 0.247 0.877 2.434]


In [128]:
# builds a database of Comp and Vout from the Virtual Nose. Set as: 0% - 20% for each component.


k=0
T={} 
for i in range (0, 10):
    comp=[0, 0, 0, 0, 0, 0, 0, 0, 0, 1000000]  
    while comp[i]<=19999:
        comp[i]=comp[i]+1
        comp[9]=comp[9]-1
        V=Voltage_Virtual_Nose(comp)
        T.update({k:[[i for i in comp],V]})
        k=k+1

In [131]:
#Creates a linear Response Model

CoLinear=np.zeros([180000,10,7])
for k in range(0, 179999):
    for j in range (0, 7):
        for i in range(0, 10):
            if T[k][1][j]!=T[k+1][1][j]:
                if T[k][0][i]!=T[k+1][0][i]:
                    CoLinear[k,i,j]=(T[k+1][0][i]-T[k][0][i])/(T[k+1][1][j]-T[k][1][j])
                
AverageK=np.zeros([7,10])
for j in range (0, 7):
        for i in range(0, 10):
            count=0
            TotalK=0
            for k in range(0, 179999):
                if CoLinear[k][i,j]!=0:
                    count=count+1
                    TotalK=TotalK + CoLinear[k][i,j]
            if count!=0:
                AverageK[j,i]=TotalK/count
            else:
                AverageK[j,i]=0         
V0comp=[0, 0, 0, 0, 0, 0, 0, 0, 0, 900000]                
V0=Voltage_Virtual_Nose(V0comp)
Vcomptest=[1000, 0, 0, 0, 0, 0, 0, 0, 0, 900000]
V=Voltage_Virtual_Nose(Vcomptest)
Caver=np.dot(V, AverageK)-np.dot(V0, AverageK)
Vp=Voltage_Virtual_Nose(Caver)
print(V)
print(Vp)
print(Caver)

[0.304 0.304 0.306 0.109 0.12  0.055 1.174]
[0.695 0.352 0.539 0.575 0.389 1.59  2.558]
[ 1.88969582e+03  1.85603395e+03  1.85607161e+03  1.84404024e+03
  5.13194771e+02  1.09156035e+03 -3.51648352e-01  0.00000000e+00
  0.00000000e+00 -1.85942829e+03]


In [228]:
V0=Voltage_Virtual_Nose(0, 0, 0, 0, 0, 0, 0, 0, 0, 900000)
V=Voltage_Virtual_Nose(0, 0, 0, 0, 10000, 0, 0, 0, 0, 900000)
Caver=np.dot(V, AverageK)-2.18*np.dot(V0, AverageK)
Vp=Voltage_Virtual_Nose(Caver[0],Caver[1], Caver[2],Caver[3],Caver[4], Caver[5],Caver[6],Caver[7], Caver[8], Caver[9])
print(V)
print(Vp)
print(Caver)


[1.611 2.401 0.113 0.109 0.12  0.055 0.054]
[2.279 3.745 1.165 1.2   4.948 0.176 1.768]
[-5867.38703523  2858.06649732  2984.77423956 -3883.62661058
  3461.69414018  -207.325911     -62.03609083   -55.22073434
   -63.73014473 -2956.18964106]
